name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.1

    - name: Add MSBuild to path
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build
      run: |
        mkdir build
        cd build

        mkdir Debug
        cd Debug
        cmake ../..
        msbuild RBTray.sln -p:Configuration=Debug -maxcpucount
        cd ..

        mkdir Release
        cd Release
        cmake ../..
        msbuild RBTray.sln -p:Configuration=Release -maxcpucount
        cd ..

        cd ..

    - name: Archive RBHook.dll
      uses: actions/upload-artifact@v2
      with:
        path: build/**/RBHook.dll

    - name: Archive RBTray.exe
      uses: actions/upload-artifact@v2
      with:
        path: build/**/RBTray.exe
