name: Build Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.1

    - name: Add MSBuild to path
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build
      run: .\vstudio_build.bat Release

    - name: Archive RBHook.dll
      uses: actions/upload-artifact@v2
      with:
        name: RBHook.dll
        path: build/vstudio/Release/RBHook.dll

    - name: Archive RBTray.exe
      uses: actions/upload-artifact@v2
      with:
        name: RBTray.exe
        path: build/vstudio/Release/RBTray.exe
