name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build
      run: msbuild RBTray.sln -p:Configuration=Release

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        path: x64/RBHook.[dll|exe]
