name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.1

    - name: Add MSBuild to path
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build Debug
      run: msbuild RBTray.sln -p:Configuration=Debug -maxcpucount

    - name: Build Release
      run: msbuild RBTray.sln -p:Configuration=Release -maxcpucount

    - name: Archive RBHook.dll
      uses: actions/upload-artifact@v2
      with:
        path: x64/**/RBHook.dll

    - name: Archive RBTray.exe
      uses: actions/upload-artifact@v2
      with:
        path: x64/**/RBTray.exe
