name: Build Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.1

    - name: Add MSBuild to path
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build
      run: .\vstudio_build.bat Release

    - name: Archive portable
      uses: actions/upload-artifact@v2
      with:
        name: portable.zip
        path: build/vstudio/Release/RB[HT][or][oa][ky].[de][lx][le]

    - name: Archive installer
      uses: actions/upload-artifact@v2
      with:
        name: RBTray-win64.exe
        path: build/vstudio/RBTray-*-win64.exe
